# West manifest for mars-cs-nrf54l
# Use with: west init -l . --mf west.yml && west update
manifest:
  version: "0.13"

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  defaults:
    remote: ncs

  projects:
    - name: nrf
      repo-path: sdk-nrf
      revision: v3.3.0
      import: true

  self:
    path: mars-cs-nrf54l
